server:
  port: 9000

spring:
  application:
    name: API-GATEWAY



  cloud:
    gateway:
      mvc:
        routes:
          - id: PRODUCT-SERVICE
            uri:  lb://PRODUCT-SERVICE
            predicates:
              - Path=/api/v1/product/**

          - id: ORDER-SERVICE
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/api/v1/order/**

          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=/api/v1/user/**

          - id: PRODUCT-SERVICE
            uri: lb://PRODUCT-SERVICE
            predicates:
              - Path=/api/v1/product/**


          - id: PRODUCT-SERVICE
            uri: lb://PRODUCT-SERVICE
            predicates:
              - Path=/api/v1/product/**



#    discovery:
#      locator:
#        enabled: true
#
#      lower-case-service-id: true